import '../styles/style.css'
import FooterRibbon from '@/components/footer/ribbon/footer_ribbon'
import HeaderRibbon from '@/components/header/ribbon/header_ribbon'
import { Noto_Serif } from 'next/font/google'

const notoSerif = Noto_Serif({
  subsets: ['cyrillic'],
});

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ru" className={notoSerif.className}>
      <body>
        <header><HeaderRibbon/></header>
          <section>
            {children}
          </section>
        <footer><FooterRibbon /></footer>
      </body>
    </html>
  )
}